name: paper2
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas>=1.3.0
  - numpy>=1.20.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scipy>=1.7.0
  - openpyxl>=3.0.0
  - xlrd>=2.0.0
  - pillow>=8.0.0
  - imageio>=2.9.0
  - ipython>=7.0.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - jupyterlab>=3.0.0