01_Hybrid_Growth/figures/final/Fig2_Metalcone_GPC.tiff: Figures/Fig2_Metalcone_GPC.tiff
01_Hybrid_Growth/figures/final/Fig2a_Metalcone_Thickness.tiff: Figures/Fig2a_Metalcone_Thickness.tiff
01_Hybrid_Growth/figures/final/Fig2b_Metalcone_GPC.tiff: Figures/Fig2b_Metalcone_GPC.tiff
02_Air_Stability/figures/final/air_stability_final.tiff: Figures/air_stability_final.tiff
03_Developer_Stability_Patterning_Contrast/figures/final/Fig4a_Heatmap_EtchStability.tiff: Figures/Fig4a_Heatmap_EtchStability.tiff
03_Developer_Stability_Patterning_Contrast/figures/final/Fig4b_Barplot_EtchStability.tiff: Figures/Fig4b_Barplot_EtchStability.tiff
03_Developer_Stability_Patterning_Contrast/figures/final/Fig4c_BarplotOrganicGroupedBySolvent.tiff: Figures/Fig4c_BarplotOrganicGroupedBySolvent.tiff
05_FTIR_Analysis/figures/final/Fig3b_FTIR_Subpanels.tiff: Figures/Fig3b_FTIR_Subpanels.tiff
06_XPS_Analysis/figures/final/BTY_XPS_Final_Publication.tiff: Figures/BTY_XPS_Final_Publication.tiff
06_XPS_Analysis/figures/final/THB_XPS_Final_Publication.tiff: Figures/THB_XPS_Final_Publication.tiff
08_E-Beam_Studies/figures/final/dose_matrix_mockup_clean.tiff: Figures/dose_matrix_mockup_clean.tiff
08_E-Beam_Studies/figures/final/box_grating_mockup_clean.tiff: Figures/box_grating_mockup_clean.tiff